version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'chore(deps):'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    commit-message:
      prefix: 'chore(ci):'

